### ISSUE TITLE
Error message - wrong data base connection?

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#105]
I got complaints from users that they get this error message:

![image1](https://cloud.githubusercontent.com/assets/7487883/8225978/db6e4fe8-159a-11e5-92e2-4acbeb5698e1.png)

I now got it myself.

Note: I have allready placed a bet on the webversion. So the app does not get the right data about the user.

I as well as users who complained have gotten the latest version and updated again today.

**Comment by mladjan** [comment]
Hi Hans,

can you go into this issue a little bit more and explain us exact situation when this happened, because Mike told me that it's happening also on Android. This means that this is not mobile related, it's web or API related problem.

**Comment by diplomod** [comment]
...or the problem exists in both app versions.

More detailed:
- I get the latest versiom from the app store.
- I login
- I choose one of the open WellBets
- I fill out the WellBet questionnaire => Error: My user has allready placed a bet - I should not be able to place it
- No error message this time
- When I check online, the results are the same as my first bet placed in the web version, not as I just did in the app.
- When I go back to the app, the results are as in the web version, not as I have posted them initially online.

We will also set up a new WellBet tonight and test what happens then.

**Comment by audriunas** [comment]
![img_0440](https://cloud.githubusercontent.com/assets/10405035/8238370/7ee88a30-15f5-11e5-826f-cf70b540f5fb.jpg)
 getting this error while trying to submit the vote on new and old wellbets.

**Comment by diplomod** [comment]
Guys,
any news?
The test with the new WellBet deluvered different results:
- No problem for me
- Did not work at all for my colleague Audrius.
  We both thave the latest version.

Do you get any error reports from the API, asks Philip.

**Comment by BorisNikolic** [comment]
Hi everybody,

I solved this issue about placing the same bet more than once. Now we are showing an alertView with the following message:"You have already placed your bet." I also fixed the issue about the data of the user, everything is working properly as far as I know. Code is updated and ready for build.
Please tell me if you run into some new issues.

Have a nice day!

**Comment by diplomod** [comment]
Hi Boris, thank you. Then please update the App in Apple App store.

BTW: Was the same issue in the Android version?

**Comment by mladjan** [comment]
Do you want first to test it on your devices because we are not 100% sure that we are thinking on the same bug/issue?

**Comment by diplomod** [comment]
Hi guys,
I still get this error message when I click on "My WellBets":

![image1](https://cloud.githubusercontent.com/assets/7487883/9656190/c7413b56-5236-11e5-8df4-1f86af84fa21.png)

This is on iPhone. Can we get this under control please?

**Comment by diplomod** [comment]
Guys, this is extremely annoying. It keeps going on, no matter how often I update the app on my phone.
The issue also appears when I try to place a bet:
![image1](https://cloud.githubusercontent.com/assets/7487883/9953498/9c99cb6e-5de1-11e5-9674-46e6470b0bee.png)

Please clarify and fix finally.

**Comment by diplomod** [comment]
@audriunas Do you have the same issue?
